server:
  port: 8080

spring:
  application:
    name: api-service
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

appointments:
  topic-name: appointments
  data-service-base-url: http://localhost:8081

---
spring:
  config:
    activate:
      on-profile: docker
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      properties:
        spring.json.add.type.headers: false

appointments:
  data-service-base-url: http://data-service:8081

